# Uvod, metoda najmanjih kvadrata, linearna regresija

In [41]:
import numpy as np

In [42]:
A = np.array([[1,2],
              [1,2.0000001]])

In [43]:
B = np.array([[1,2],[3,4]])

In [44]:
# pokoordinatno mnozenje
A * B

array([[1.       , 4.       ],
       [3.       , 8.0000004]])

In [45]:
# matricno mnozenje
A.dot(B)

array([[ 7.       , 10.       ],
       [ 7.0000003, 10.0000004]])

In [46]:
from numpy import linalg as LA

In [47]:
LA.det(A)

9.999999983634205e-08

In [48]:
LA.inv(A)

array([[ 20000001.03273158, -20000000.03273158],
       [-10000000.01636579,  10000000.01636579]])

In [49]:
LA.cond(A)

100000003.8939614

In [50]:
# LA.lstsq()

Odrediti koeficijente w0 i w1 tako da funkcija 𝑓(𝑥)=w0+w1𝑥 u smislu metode najmanjih kvadrata najbolje aproksimira skup tačaka (0,1.2), (0.5,2.05), (1,2.9) i (−0.5,0.1) u ravni.

In [51]:
xs = np.array([0, 0.5, 1, -0.5])
ys = np.array([1.2, 2.05, 2.9, 0.1])


In [52]:
X = np.ones((2, xs.shape[0]))
X[1] = xs
X

array([[ 1. ,  1. ,  1. ,  1. ],
       [ 0. ,  0.5,  1. , -0.5]])

In [53]:
# np.vstack((np.ones(3), np.zeros(3)))

In [54]:
w, res, _, _ = LA.lstsq(X.T, ys, rcond=None)

In [48]:
w

array([1.1 , 1.85])

In [49]:
res

array([0.01875])

In [58]:
((1.1 + 1.85 * xs - ys) ** 2).sum()

0.01874999999999998

In [56]:
# broadcasting
# A + np.ones(3)

Odrediti vrednosti koeficijenata 𝑎 i 𝑏 tako da funkcija 𝑓(𝑥)=𝑎+𝑏sin𝑥 u smislu metode najmanjih kvadrata aproksimira skup tacaka (2,2.6), (−1.22,−1.7), (8.32,2.5) i (4.23,−1.6) u ravni. Dati ocenu greske. Prikazati skup tačaka i nacrtati rezultujucu funkciju

In [59]:
xs = np.array([2, -1.22, 8.32, 4.23])
ys = np.array([2.6, -1.7, 2.5, -1.6])

In [61]:
# X = ...np.sin(xs)

Svaki red u fajlu advertising.csv sadrži informacije o cenama u hiljadama dolara reklamnih usluga na određenom tržištu. Prva kolona se odnosi na cene reklamiranja na televiziji, druga na radiju, a treća u novinama. Četvrta kolona se odnosi na ukupnu prodaju proizvoda koji su se reklamirali na datim medijima. Kreirati linearni model koji predviđa prodaju na osnovu cena reklamiranja.

In [1]:
import pandas as pd

In [3]:
df = pd.read_csv('Materijali-sa-vezbi/2023_2024/live/01_linear_regression/advertising.csv')

In [6]:
X = df.drop('Sales', axis=1)
X

TV  Radio  Newspaper
0    230.1   37.8       69.2
1     44.5   39.3       45.1
2     17.2   45.9       69.3
3    151.5   41.3       58.5
4    180.8   10.8       58.4
..     ...    ...        ...
195   38.2    3.7       13.8
196   94.2    4.9        8.1
197  177.0    9.3        6.4
198  283.6   42.0       66.2
199  232.1    8.6        8.7

[200 rows x 3 columns]

In [7]:
y = df['Sales']
y

0      22.1
1      10.4
2       9.3
3      18.5
4      12.9
       ... 
195     7.6
196     9.7
197    12.8
198    25.5
199    13.4
Name: Sales, Length: 200, dtype: float64

In [8]:
from sklearn.linear_model import LinearRegression

In [15]:
model = LinearRegression()

In [16]:
from sklearn.model_selection import train_test_split

In [29]:
X_train, X_test, y_train, y_test = train_test_split(X, y, train_size=0.75)

In [55]:
from sklearn.preprocessing import StandardScaler

In [31]:
# ne moramo jer su na istim skalama
# scaler = StandardScaler()
# scaler.fit(X_train)
# X_train = scaler.transform(X_train)
# X_test = scaler.transform(X_test)

In [32]:
model.fit(X_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [33]:
model.coef_

array([ 3.50834368,  2.91013966, -0.09451508])

In [34]:
model.intercept_

14.262

In [35]:
# interpretabilnost
# y_pred = 2.9 + 0.05*x1 + 0.19*x2 - 0.001*x3

In [36]:
y_pred = model.predict(X_test)

In [37]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

In [38]:
mean_squared_error(y_test, y_pred)

6.1750905983719235

In [39]:
mean_absolute_error(y_test, y_pred)

1.8541785123886247

In [40]:
r2_score(y_test, y_pred)

0.8016556675227332